### ISSUE TITLE
No ratings displayed.

### ISSUE THREAD

**Issue by Alanon202** [JourneyDeprecated/My-Userstyles#2]
The theme never displays ratings. In the original layout, if an episode, season, show or movie is rated, there's a small red patch in the upper right corner showing the given rating. This is true both on posters and episode thumbs, on all sort methods and views. 

I've tested on versions between 2.4.2-2.4.6 and the behaviour is the same. It's the one thing preventing me from using the theme full-time.

**Comment by JourneyOver** [comment]
Issue has now been fixed in 2.4.7 (already uploaded to userstyles.org) ^^ sorry about that, I totally forgot about ratings not showing up as I haven't rated anything in forever. If they are not showing up for you still after you install 2.4.7 let me know.

**Comment by Alanon202** [comment]
Brilliant!
